create table if not exists public.user_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique
    check (
      username ~ '^[a-z0-9][a-z0-9._-]{2,18}[a-z0-9_-]$'
      and username !~ '\.\.'
    ),
  recovery_question text not null,
  recovery_answer_salt text not null,
  recovery_answer_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.password_recovery_attempts (
  id bigint generated by default as identity primary key,
  username text not null,
  action text not null check (action in ('signup', 'question', 'reset')),
  ip_hash text not null,
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists password_recovery_attempts_username_created_idx
  on public.password_recovery_attempts (username, action, created_at desc);

create index if not exists password_recovery_attempts_ip_created_idx
  on public.password_recovery_attempts (ip_hash, action, created_at desc);

alter table public.user_accounts enable row level security;
alter table public.password_recovery_attempts enable row level security;

revoke all on table public.user_accounts from anon, authenticated;
revoke all on table public.password_recovery_attempts from anon, authenticated;
