create table if not exists public.pronunciation_skip_words (
  id bigint generated by default as identity primary key,
  phrase text not null
    check (char_length(trim(phrase)) between 1 and 50),
  normalized_phrase text not null unique
    check (char_length(normalized_phrase) between 1 and 50),
  created_at timestamptz not null default now()
);

alter table public.pronunciation_skip_words enable row level security;
revoke all on table public.pronunciation_skip_words from anon, authenticated;
